**Least Cost Path Assignment**

**Important instructions**

- Read the notes **LeastCostPathInRectangularGrid.pdf** file carefully. I spent a lot of time writing these. Understanding what is contained in these notes is critical to getting on top of this assignment.

- There is also a **video** that goes over the dynamic programming approach in an example. If you are confused about how dynamic programming is supposed to work, **watch the video.**

- When asked to provide a function, your code will be tested on examples and so it is important that you follow the specifications exactly.

    - the **input** parameters should have the types specified 
    - the **outputs** should have the types specified



In [4]:
import numpy as np
import pandas as pd
from sympy.utilities.iterables import multiset_permutations

**Sympy**

We will use the **sympy** package to since it allows us to generate all possible permutations of the elements of a list. The list can consist of identical values, hence the term *multiset*. As you are hopefully all aware, the number of permutations of aaabb is Binomal(5,3) = 10.

In [5]:
perms=multiset_permutations(["a","a","a","b","b"])
for p in perms:
    print(p)

['a', 'a', 'a', 'b', 'b']
['a', 'a', 'b', 'a', 'b']
['a', 'a', 'b', 'b', 'a']
['a', 'b', 'a', 'a', 'b']
['a', 'b', 'a', 'b', 'a']
['a', 'b', 'b', 'a', 'a']
['b', 'a', 'a', 'a', 'b']
['b', 'a', 'a', 'b', 'a']
['b', 'a', 'b', 'a', 'a']
['b', 'b', 'a', 'a', 'a']


**Saving and Loading Numpy Arrays**

H and V arrays for sample problems have been created using code in the **ProblemFiles.ipynb** file. You can see there that these arrays are created using a numpy random number generator. The numpy **save** command is used to save the files. Whatever file name is used as an argument, by default the suffix *".npy"*  is appended to the file name, and the file is saved in a format that can be rea using **in any platform** using the numpy **load** command.

In the code below several numpy arrays are loaded. **You should not modify these arrays anywhere in the notebook.**

You will need to run the following code in order to store these arrays.

In [6]:
# Do no modify or delete this cell
# Do execute it.
H1=np.load("H1.npy")
V1=np.load("V1.npy")
print(H1)
print("\n")
print(V1)
H2=np.load("H2.npy")
V2=np.load("V2.npy")
H3=np.load("H3.npy")
V3=np.load("V3.npy")
H4=np.load("H4.npy")
V4=np.load("V4.npy")
H5=np.load("H5.npy")
V5=np.load("V5.npy")

[[0.27223497 0.37107017 0.0615633 ]
 [0.52189173 0.64237414 0.25185655]
 [0.69765257 0.41819083 0.87060541]
 [0.07185002 0.25671929 0.75904716]
 [0.93844977 0.8359802  0.0891893 ]]


[[0.17712688 0.44517639 0.48319163 0.88850449]
 [0.903064   0.45611378 0.2187896  0.5370547 ]
 [0.9064702  0.3652126  0.62288606 0.7077785 ]
 [0.52447404 0.98297599 0.3645919  0.7418832 ]]


**Problem 1 (10 points)**

Write a function called **GetIndicesOfPath** that takes as input a 


- **path**, which is **list** of individual characters in the set {"H","V"} 

and outputs 

- a **list** of **2-tuples** giving the pairs of indices $(I,J)$ corresponding to positions in a matrix starting from $(0,0)$ and ending with $(m,n)$ where $m$ is the number of V's in the path, and $n$ is the number of H's in the path.

So for example, if $m=2$ and $n=3$ the path ['H','H','V','V','H'] should give as output the *list*
[(0,0),(0,1),(0,2),(1,2),(2,2),(2,3)]

Use the following cell for you code.

In [7]:
# Code cell for Problem 1 - do not remove or modify this line
def GetIndicesOfPath(path):
    L=[]
    L.append((0,0))
    k=0
    for i in path:
        if i=='H':
            L.append(tuple(map(lambda i,j: i+j, (0,1), L[k])))
        else:
            L.append(tuple(map(lambda i,j: i+j, (1,0), L[k])))
        k+=1
    return L

In [8]:
# Test cell1 for Problem 1 - do not delete or modify this cell
# Do execute it
path=['H','H','V','V','H']
print(GetIndicesOfPath(path))

[(0, 0), (0, 1), (0, 2), (1, 2), (2, 2), (2, 3)]


In [9]:
# Test cell2 for Problem 1 - do not delete or modify this cell
# Do execute it
np.random.seed(1418941)
m=16
n=9
HVlist=["V" for i in range(m)]+["H" for i in range(n)]
path=list(np.random.permutation(HVlist))
print(path)
GetIndicesOfPath(path)

['V', 'V', 'H', 'V', 'V', 'H', 'V', 'H', 'V', 'H', 'H', 'V', 'V', 'H', 'V', 'V', 'H', 'V', 'V', 'H', 'H', 'V', 'V', 'V', 'V']


[(0, 0),
 (1, 0),
 (2, 0),
 (2, 1),
 (3, 1),
 (4, 1),
 (4, 2),
 (5, 2),
 (5, 3),
 (6, 3),
 (6, 4),
 (6, 5),
 (7, 5),
 (8, 5),
 (8, 6),
 (9, 6),
 (10, 6),
 (10, 7),
 (11, 7),
 (12, 7),
 (12, 8),
 (12, 9),
 (13, 9),
 (14, 9),
 (15, 9),
 (16, 9)]

**Problem 2 (10 points)**

Write a function called **PathCost** that takes as inputs the following:

- two positive integers **m** and **n**, giving grid dimenssions, 
- a numpy array **H** ($m+1 \times n$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i,j+1),$ and
- a numpy array **V** ($m \times n+1)$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i+1,j)$
- a **path**, which is a list of characters of size $m+n$ consisting of $m$ V's and $n$ H's. 

and as output the cost of moving from $(0,0)$ to $(m,n)$ defined by the horizontal and vertical moves in path.

Use the following cell for your code.

In [10]:
# Code cell for Problem 2 - do not remove or modify this line
def PathCost(m,n,H,V,path): 
    ind = GetIndicesOfPath(path)
    cost=0
    k=0
    for i in path:
        t0=ind[k][0]
        t1=ind[k][1]
        if i=='H':
            cost+=H[t0][t1]
        else:
            cost+=V[t0][t1]
        k+=1
    return cost

In [11]:
# Test cell1 for Problem 2 - do not delete or modify this cell
# Do execute it
np.random.seed(114183491)
m=2
n=2
H=np.random.choice(range(1,5),size=(m+1,n))
V=np.random.choice(range(1,5),size=(m,n+1))
HVlist=['V' for i in range(m)]+['H' for i in range(n)]
print(H)
print(V)
path1=list(np.random.permutation(HVlist))
print(path1)
print(PathCost(m,n,H,V,path1))
path2=list(np.random.permutation(HVlist))
print(path2)
print(PathCost(m,n,H,V,path2))


[[2 2]
 [1 2]
 [4 1]]
[[1 3 4]
 [4 3 4]]
['V', 'H', 'V', 'H']
6
['H', 'V', 'V', 'H']
9


In [12]:
# Test cell for Problem 2 - do not delete or modify this cell
# Do execute it
np.random.seed(1183491)
m=15
n=73
H=np.random.choice(range(1,5),size=(m+1,n))
V=np.random.choice(range(1,5),size=(m,n+1))
HVlist=['V' for i in range(m)]+['H' for i in range(n)]
path=list(np.random.permutation(HVlist))
print(path)
print(H)
print(V)
print(PathCost(m,n,H,V,path))

['V', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'V', 'V', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'V', 'H', 'H', 'H', 'H', 'V', 'H', 'H', 'V', 'H', 'H', 'H', 'H', 'V', 'H', 'H', 'V', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'V', 'H', 'H', 'H', 'H', 'H', 'H', 'V', 'H', 'V', 'H', 'H', 'V', 'V', 'H', 'H', 'H', 'V', 'H', 'V', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']
[[4 4 1 ... 4 4 2]
 [3 1 3 ... 3 2 4]
 [1 4 4 ... 4 1 2]
 ...
 [4 3 1 ... 4 3 3]
 [1 2 2 ... 3 4 4]
 [3 3 4 ... 2 2 2]]
[[3 1 2 ... 1 4 2]
 [4 4 3 ... 3 4 1]
 [4 2 4 ... 4 3 3]
 ...
 [2 3 3 ... 2 3 1]
 [1 2 2 ... 4 4 1]
 [1 3 2 ... 3 1 2]]
231


**Problem 3 (10 points)**

Write a function called **LeastCostPathBruteForce** that takes as input

- two positive integers **m** and **n**, giving grid dimensions, 
- a numpy array **H** ($m \times (n+1)$) giving, in position $(i,j)$ the cost of a horizontal move from $(i,j)$ to $(i,j+1),$ and
- a numpy array **V** ($m+1 \times n)$ giving, in postion $(i,j)$ the cost of a vertical move from $(i,j)$ to $(i+1,j)$

and as output gives a 2-tuple containing (in the following order):

- the **cost** (a number) of a least cost path from $(0,0)$ to $(m,n)$ **rounded to 3 decimal places,** and 
- an optimal path, which should be a list of 2-tuples [(0,0),....,(m,n)] giving nodes visited along an optimal path *in order*.

Your function should solve the problem using the **brute-force** approach of iterating over all possible paths.

It is always a good idea to test your code problems where a brute-force solution can be found. This code will not be useful practically for large values of $m$ and $n$ but you **can** use it for testing purposes. 

It would be wise to test your code on some small examples. You can use this notebook for that purpose. Please do not use any of the cell headings I created in this notebook.

Use the following cell for your code.

In [13]:
# Code cell for Problem 3 - do not delete or modify this line
def LeastCostPathBruteForce(m,n,H,V):
    HVlist=['V' for i in range(m)]+['H' for i in range(n)]
    paths=multiset_permutations(HVlist)
    cost=10**100
    path_opt=[]
    import math as math
    k=math.comb(m+n,n)
    print(len(str(k)))
    print(m,n)
    print(f"number of paths = {k}")
    i=0
    f=2300
    m=0
    for path in paths:
        i += 1
        if i/k >  m/f:
            m+=1
            print(f"progress = {i/k*100: 0.7f}%") 
        c = PathCost(m,n,H,V,path)
        if c < cost:
            cost = c
            path_opt = path
    return np.round(cost,3), path_opt

**Problem 4 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H1, V1 example. 

In [14]:
# Test cell for Problem 4 - do not delete or modify this cell
# Do execute it.
np.random.seed(114183491)
LeastCostPathBruteForce(4,3,H1,V1)

2
4 3
number of paths = 35
progress =  2.8571429%
progress =  5.7142857%
progress =  8.5714286%
progress =  11.4285714%
progress =  14.2857143%
progress =  17.1428571%
progress =  20.0000000%
progress =  22.8571429%
progress =  25.7142857%
progress =  28.5714286%
progress =  31.4285714%
progress =  34.2857143%
progress =  37.1428571%
progress =  40.0000000%
progress =  42.8571429%
progress =  45.7142857%
progress =  48.5714286%
progress =  51.4285714%
progress =  54.2857143%
progress =  57.1428571%
progress =  60.0000000%
progress =  62.8571429%
progress =  65.7142857%
progress =  68.5714286%
progress =  71.4285714%
progress =  74.2857143%
progress =  77.1428571%
progress =  80.0000000%
progress =  82.8571429%
progress =  85.7142857%
progress =  88.5714286%
progress =  91.4285714%
progress =  94.2857143%
progress =  97.1428571%
progress =  100.0000000%


(2.231, ['V', 'H', 'V', 'V', 'H', 'V', 'H'])

**Problem 5 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H2, V2 example. 

In [15]:
# Test cell for Problem 5 - do not delete or modify this cell
# Do execute it.
LeastCostPathBruteForce(5,8,H2,V2)

4
5 8
number of paths = 1287
progress =  0.0777001%
progress =  0.1554002%
progress =  0.2331002%
progress =  0.3108003%
progress =  0.3885004%
progress =  0.4662005%
progress =  0.5439005%
progress =  0.6216006%
progress =  0.6993007%
progress =  0.7770008%
progress =  0.8547009%
progress =  0.9324009%
progress =  1.0101010%
progress =  1.0878011%
progress =  1.1655012%
progress =  1.2432012%
progress =  1.3209013%
progress =  1.3986014%
progress =  1.4763015%
progress =  1.5540016%
progress =  1.6317016%
progress =  1.7094017%
progress =  1.7871018%
progress =  1.8648019%
progress =  1.9425019%
progress =  2.0202020%
progress =  2.0979021%
progress =  2.1756022%
progress =  2.2533023%
progress =  2.3310023%
progress =  2.4087024%
progress =  2.4864025%
progress =  2.5641026%
progress =  2.6418026%
progress =  2.7195027%
progress =  2.7972028%
progress =  2.8749029%
progress =  2.9526030%
progress =  3.0303030%
progress =  3.1080031%
progress =  3.1857032%
progress =  3.2634033%
progr

(4.606, ['H', 'H', 'H', 'H', 'H', 'H', 'V', 'V', 'V', 'V', 'H', 'V', 'H'])

**Problem 6 (26 points)**

Write code that takes the **same inputs** and gives the **same outputs** as in the **LeastCostPathBruteForce** function, but this time solving the problem using dynamic programming as described in the *LeastCostPathInRectangularGrid.pdf* document. Call this function **LeastCostPathDynamicProgramming**.

**Make sure** you round your least cost solution to 3 decimal places.

You should test your code on random cases when m and n are small enough so that the brute-force method can be applied and you should get the same answers using the two methods provided that there is no possibility of multiple optimal paths. (This will have a **very small probability** if you take V and H to be random with uniformly distributed entries.)

Again, if you add your own test cells, do not use any of the cell headers that have been used in this notebook.

Use the following cell for your function. 

In [20]:
# Code cell for Problem 6 - do not delete or modify this line
def LeastCostPathDynamicProgramming(m,n,H,V):
    C=np.zeros((m+1,n+1))
    D=[['' for i in range(n+1)] for j in range(m+1)]
    for i in range(1,m+1):
        C[i][0]=np.sum([V[c][0] for c in range(i)])
        D[i][0]='V'
    for j in range(1,n+1):
        C[0][j]=np.sum(H[0][0:j])
        D[0][j]='H'

    k=m*n
    print(f"number of paths = {k}")
    f=17
    d=1
    ell=0
    for i in range(1,m+1):
        for j in range(1,n+1):
            ell += 1
            if ell/k > d/f:
                d+=1
                print(f"progress = {ell/k*100: 0.7f}%") 

            if C[i-1][j]+V[i-1][j] <= C[i][j-1]+H[i][j-1]:
                C[i][j]=C[i-1][j]+V[i-1][j]
                D[i][j]='V'
            else:
                C[i][j]=C[i][j-1]+H[i][j-1]
                D[i][j]='H'
    print(C)
    path=[(m,n)]
    Path=[]
    cost=C[m,n]
    while len(path) < m+n+1:
        t = path[len(path)-1]
        indx=t[0]
        indy=t[1]
        if D[indx][indy] == 'V':
            path.append((indx-1,indy))
            Path.append('V')
        else:
            path.append((indx,indy-1))
            Path.append('H')
    print(D)
    return np.round(cost,3), Path[::-1]

**Problem 7 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H1, V1 example. 

In [21]:
# Test cell for Problem 7 - do not delete or modify this cell
# Do execute it.
LeastCostPathDynamicProgramming(4,3,H1,V1)

number of paths = 12
progress =  8.3333333%
progress =  16.6666667%
progress =  25.0000000%
progress =  33.3333333%
progress =  41.6666667%
progress =  50.0000000%
progress =  58.3333333%
progress =  66.6666667%
progress =  75.0000000%
progress =  83.3333333%
progress =  91.6666667%
progress =  100.0000000%
[[0.         0.27223497 0.64330514 0.70486845]
 [0.17712688 0.69901861 1.12649677 1.37835332]
 [1.08019088 1.15513238 1.34528637 1.91540802]
 [1.98666108 1.52034498 1.77706427 2.53611143]
 [2.51113512 2.50332098 2.14165617 2.23084547]]
[['', 'H', 'H', 'H'], ['V', 'H', 'V', 'H'], ['V', 'V', 'V', 'V'], ['V', 'V', 'H', 'H'], ['V', 'V', 'V', 'H']]


(2.231, ['V', 'H', 'V', 'V', 'H', 'V', 'H'])

**Problem 8 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H2, V2 example. 


In [18]:
# Test cell for Problem 8 - do not delete or modify this cell
# Do execute it.

LeastCostPathDynamicProgramming(5,8,H2,V2)

number of paths = 40
progress =  7.5000000%
progress =  12.5000000%
progress =  20.0000000%
progress =  25.0000000%
progress =  30.0000000%
progress =  37.5000000%
progress =  42.5000000%
progress =  47.5000000%
progress =  55.0000000%
progress =  60.0000000%
progress =  65.0000000%
progress =  72.5000000%
progress =  77.5000000%
progress =  82.5000000%
progress =  90.0000000%
progress =  95.0000000%
[['', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'], ['V', 'H', 'H', 'V', 'V', 'V', 'V', 'H', 'V'], ['V', 'V', 'H', 'V', 'V', 'V', 'V', 'V', 'V'], ['V', 'H', 'V', 'V', 'V', 'V', 'V', 'H', 'V'], ['V', 'V', 'H', 'H', 'H', 'V', 'V', 'H', 'H'], ['V', 'H', 'H', 'V', 'V', 'H', 'V', 'V', 'H']]


(4.606, ['H', 'H', 'H', 'H', 'H', 'H', 'V', 'V', 'V', 'V', 'H', 'V', 'H'])

**Problem 9 (2 points)**

Run the code in the following cell to determine the optimal cost and optimal path in the H3, V3 example. 

In [19]:
import time as time
np.random.seed(10)
m=4719
n=2342

H=np.random.choice(range(1,5),size=(m+1,n))/np.e
V=np.random.choice(range(1,5),size=(m,n+1))/np.pi
run1=0
run2=1
if run1 == 1:
    start=time.time()
    c1, p1=LeastCostPathBruteForce(m,n,H,V)
    t1=time.time()-start
    print(f"time1 = {t1:0.9f}, cost = {c1:.3f}, path = {p1}")

if run2 == 1:
    start=time.time()
    c2, p2=LeastCostPathDynamicProgramming(m,n,H,V)
    t2=time.time()-start
    print(f"time2 = {t2:0.9f}, cost = {c2:.3f}, path = {p2}")


number of paths = 11051898
progress =  5.8823561%
progress =  11.7647123%
progress =  17.6470594%
progress =  23.5294155%
progress =  29.4117716%
progress =  35.2941187%


KeyboardInterrupt: 

In [ ]:
# Test cell for Problem 9 - do not delete or modify this cell
# Do execute it.
LeastCostPathDynamicProgramming(40,30,H3,V3)

**Problem 10 (2 points)**

Run the code in the following cell to determine the optimal cost in the H4, V4 example. 

**You should not modify the cell - just run it.**

In [ ]:
# Test cell for Problem 10 - do not delete or modify this cell
# Do execute it.
LeastCostPathDynamicProgramming(400,300,H4,V4)[0]

**Problem 11 (2 points)**

Run the code in the following cell to determine the optimal cost in the H5, V5 example. 

**You should not modify the cell - just run it.**

In [ ]:
# Test cell for Problem 11 - do not delete or modify this cell
# Do execute it.
LeastCostPathDynamicProgramming(800,1000,H5,V5)[0]